export const zugTexts = [
    "Beletörődtem sorsomba...",
    "Küldd, amíg meleg!",
    "Ez is az én hibám volt.",
    "Egészségemre, többé-kevésbé!",
    "Na jó, csak most az egyszer... újra.",
    "Torkon csúszik, mint a vereség.",
    "Koccintsunk... velem. Egyedül.",
    "Legalább nem víz.",
    "Ezt is megiszom helyettetek.",
    "Vesztesként is győztes vagyok... a májgyilkolásban.",
    "A zugivó cím büszke tulajdonosa lettem!",
    "Csak a gyengék nem bírják. Én sem.",
    "Nem is vagyok szomjas... még.",
    "Ez az utolsó... talán.",
    "Csak a májam tiltakozik.",
    "Szóljon valaki anyunak!",
    "Így kezdődnek a legendák... vagy a másnapok.",
    "Fel a fejjel, le a feles!",
    "A szabályok kegyetlenek, mint ez a pálinka.",
    "Zugivás? Ez már művészet.",
    "Nem vesztettem, csak inni akartam.",
    "Így jár, aki lassan nyomja a gombot.",
    "Ez fájni fog... holnap.",
    "Ha már nem nyerek, legalább igyak.",
    "A pohár sosem ürül ki.",
    "Győzelem helyett gyomorégés.",
    "Ennyi volt, most meginni kötelező.",
    "Ha bukok, iszom. Ha nyerek, iszom.",
    "Én vagyok a saját ellenségem.",
    "Koccintsunk a balsorsra!",
    "Leraktam a fegyvert... felemeltem a poharat.",
    "Most már biztosan nem vezetek haza.",
    "Ez a korty az én epitáfiumom.",
    "Legalább a pohár megért engem.",
    "Elestem a csatában, de győztem a kocsmában.",
    "Vége a játéknak, kezdődik a mámor.",
    "Kiütöttek... vagyis leütöttem magam.",
    "Ezt már a májam ügyvédje sem menti meg.",
    "Én nem vesztettem, csak taktikusan ittam.",
    "Kösz, játék... most már a WC következik.",
    "Ha bukni kell, bukjunk stílussal.",
    "Ez most csúszni fog.",
    "Legalább nem volt unalmas.",
    "A vég mindig egy pohárban lapul.",
    "Érzem, ahogy oldódik a józan eszem.",
    "Inkább így, mint másképp.",
    "Most egy korty, aztán majd meglátjuk.",
    "A vesztesek klubjába tartozom.",
    "Az igazi fődíj: fejfájás.",
    "Vesztettem, de a pohár tele van.",
    "Ha nincs győzelem, jó lesz a szesz is.",
    "Ezt a kört elbuktam... szó szerint.",
    "A játék véget ért, de az ivás folytatódik.",
    "Koccintsunk a vereségre!",
    "A bukás íze erősen éget.",
    "Sorscsapás? Nem, csak még egy feles.",
    "Most már a szőnyeg lesz a legjobb barátom.",
    "Jöhet a gyomorpróba.",
    "Inkább igyak, mint unatkozzak.",
    "Megadom magam, pohárral a kézben.",
    "Így jár, aki nem figyel.",
    "Az élet rövid, a pohár mély.",
    "Minden veszteség egy korttyal ér véget.",
    "Hát ez most betalált.",
    "Újabb hiba, újabb pohár.",
    "Én kérek elnézést, májam.",
    "Kinek kell győzelem, ha van alkohol?",
    "Ez volt a taktika... csak rossz.",
    "Veszíteni is tudni kell... kortyolva.",
    "Így kezdődik a ballada a zugivóról.",
    "Ez a kör most elnyelt.",
    "Nem hittem volna, hogy eddig bírom.",
    "Pálinkában erősebb vagyok, mint a játékban.",
    "Megint elcsúsztam, mint a kupica.",
    "Lehúzom a vereséget.",
    "Szóljon a harang... vagy a koccintás.",
    "Az ital vigasztal, a játék cserbenhagy.",
    "Na jó, ez most fájni fog.",
    "Kihagytam a győzelmet, de nem a poharat.",
    "Zuglás, bukás, kortyolás.",
    "Ez a vereség égeti a torkom.",
    "Nem maradt más, csak a pohár.",
    "Újabb korty, újabb esély.",
    "Ha a játék nem megy, az ivás mindig igen.",
    "Ez most nem jött össze, de lemegy.",
    "Kocc a hibákra!",
    "A májam már tiltakozik.",
    "Ez a vereség kísérteni fog.",
    "Érzem, ahogy süllyedek... a pohár fenekére.",
    "Lehajtva minden szebb.",
    "Legalább nem volt hiába.",
    "Ez most betalált, mint a pálinka reggelire.",
    "Nincs kiút, csak az üveg alja.",
    "A vereség íze keserűbb, mint ez az ital.",
    "Részeg logika: veszteni jó.",
    "Néha a legjobb játékos is hibázik... és iszik.",
    "A vereség a győzelem része... vagy a másnapé.",
    "Most már biztos, hogy vesztettem.",
    "Ha más nem, az üveg legalább nyer.",
    "Ez a korty az ítéletem.",
    "Kocc a balszerencsére!",
    "Inkább így, mint szomjasan.",
    "A veszteség íze szeszben mérhető.",
    "Ez most hatni fog.",
    "Lehajtva minden könnyebb.",
    "Legalább a játék szórakoztatott.",
    "Ez a kör nem az enyém volt.",
    "Jöhet a következő... pohár.",
    "A májam már sír.",
    "Megint csak egy hiba, megint csak egy korty.",
    "Ezt nem úszom meg szárazon.",
    "Most már tényleg éget.",
    "Addig járt a korsó a kútra, míg el nem tört.",
    "Elestem, de a pohár felsegít.",
    "Ez volt a végszó.",
    "Nincs mit tenni, inni kell.",
    "Az alkohol vigaszt nyújt.",
    "Megint én vagyok a vesztes hős.",
    "Ez most nagyon csípett.",
    "Jobb inni, mint megint nyerni?",
    "Kocc a hibákra és a vereségre.",
    "Ha ez nem győzelem, akkor mi?",
    "A májam feladta.",
    "Ez a játék nekem ivóverseny.",
    "Buktam, mint a részeg osztó.",
    "Legalább a poén kedvéért.",
    "Most már biztos, hogy holnap fájni fog.",
    "A vereség keserű, az ital erősebb.",
    "Nem nyertem, de lett egy kortyom.",
    "Én így ünneplek.",
    "Legalább a sör hideg.",
    "Ez a játék nem kegyelmez.",
    "Kocc a bukásra.",
    "Ha már így alakult, lehúzom.",
    "A vereség hangja: kocc.",
    "Így lettem zugivó bajnok.",
    "Nem számít, mennyit bukok, mindig iszom.",
    "Ez most betalált, nagyon.",
    "A pohár a barátom.",
    "Kocc, és felejtsük el.",
    "Nem is olyan rossz vesztesnek lenni.",
    "Egy kortyban minden bánat.",
    "Ez most szíven ütött... és gyomron.",
    "A vereség könnyebben csúszik alkohollal.",
    "Ez már túl sok volt.",
    "Jobb inni, mint sírni.",
    "A bukás része a játéknak.",
    "Ez a kör az italé.",
    "Lehúztam, mint a szerencsém.",
    "Koccintsunk a balsorsra!",
    "Ez a veszteség erősebb, mint a pia.",
    "Megint hibáztam, megint ittam.",
    "Az utolsó szó mindig az italé.",
    "Nem nyerhetek mindig, de ihatok mindig.",
    "Legalább a májam dolgozik.",
    "A vereség után könnyebb inni.",
    "Ez most tényleg betalált.",
    "Minden veszteség egy korttyal ér véget.",
    "Ha más nem, az ital mindig nyer.",
    "Ez volt a végszó: igyál!",
    "Kocc a hibákra, kocc a májra.",
    "Legalább van mentségem az ivásra.",
    "Ez most nem jött össze.",
    "Újabb kör, újabb pohár.",
    "A vereség íze erősebb, mint a győzelem.",
    "Ez most a sors ajándéka.",
    "Legalább szórakoztam közben.",
    "A hibák mindig egy pohárba vezetnek.",
    "Most már biztosan zugivó vagyok.",
    "Ez a játék keményebb, mint gondoltam.",
    "Megint hibáztam, megint lehúztam.",
    "A vereség mindig édesebb egy korttyal.",
    "Ez most a vég kezdete.",
    "Legalább az ital megvigasztal.",
    "Minden pohár egy emlék.",
    "Ez most nagyon betalált.",
    "Nincs győzelem, csak szesz.",
    "Legalább nem unatkozom.",
    "Ez most csípett.",
    "Minden bukás után egy korty.",
    "Ez most a játékom vége.",
    "Legalább jó ürügy volt inni."
];